spring:
  application:
    name: ${vcap.application.name:eureka-sample}
  cloud:
    services:
      registrationMethod: route

server:
  port: 8081

security:
  basic:
    enabled: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    hostname: ${vcap.application.uris[0]:localhost}
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

shutdown.delay: 5