spring:
  application:
    name: ${vcap.application.name:eureka-sample}
  cloud:
    services:
      registrationMethod: route

server:
  port: 8081

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    hostname: ${vcap.application.uris[0]:localhost}
    metadataMap:
      instanceId: ${vcap.application.instance_index:spring.application.instance_id}

shutdown.delay: 5